[package]
name = "image-blur"
version = "0.1.0"
edition = "2024"

[dependencies]
actix = "0.13.5"
actix-web = "4.11.0"
image = "0.25.6"
reqwest = { version= "0.12.12", features = ["json","blocking"] }

serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.140"
